// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file common.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SBmNvbW1vbiIxCg1Ub2tlbkxhbXBvcnRzEg4KBmFtb3VudBgBIAEoBBIQCghkZWNpbWFscxgCIAEoDSIYCgdEZWNpbWFsEg0KBXZhbHVlGAEgASgJIhwKDFRva2VuQWRkcmVzcxIMCgRtaW50GAEgASgJIiIKDVVuaXhUaW1lc3RhbXASEQoJdGltZXN0YW1wGAEgASgDKh4KCVF1b3RlS2luZBIHCgNTT0wQABIICgRVU0RDEAFiBnByb3RvMw");

/**
 * @generated from message common.TokenLamports
 */
export type TokenLamports = Message<"common.TokenLamports"> & {
  /**
   * @generated from field: uint64 amount = 1;
   */
  amount: bigint;

  /**
   * @generated from field: uint32 decimals = 2;
   */
  decimals: number;
};

/**
 * Describes the message common.TokenLamports.
 * Use `create(TokenLamportsSchema)` to create a new message.
 */
export const TokenLamportsSchema: GenMessage<TokenLamports> = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * @generated from message common.Decimal
 */
export type Decimal = Message<"common.Decimal"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message common.Decimal.
 * Use `create(DecimalSchema)` to create a new message.
 */
export const DecimalSchema: GenMessage<Decimal> = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * @generated from message common.TokenAddress
 */
export type TokenAddress = Message<"common.TokenAddress"> & {
  /**
   * @generated from field: string mint = 1;
   */
  mint: string;
};

/**
 * Describes the message common.TokenAddress.
 * Use `create(TokenAddressSchema)` to create a new message.
 */
export const TokenAddressSchema: GenMessage<TokenAddress> = /*@__PURE__*/
  messageDesc(file_common, 2);

/**
 * @generated from message common.UnixTimestamp
 */
export type UnixTimestamp = Message<"common.UnixTimestamp"> & {
  /**
   * @generated from field: int64 timestamp = 1;
   */
  timestamp: bigint;
};

/**
 * Describes the message common.UnixTimestamp.
 * Use `create(UnixTimestampSchema)` to create a new message.
 */
export const UnixTimestampSchema: GenMessage<UnixTimestamp> = /*@__PURE__*/
  messageDesc(file_common, 3);

/**
 * @generated from enum common.QuoteKind
 */
export enum QuoteKind {
  /**
   * @generated from enum value: SOL = 0;
   */
  SOL = 0,

  /**
   * @generated from enum value: USDC = 1;
   */
  USDC = 1,
}

/**
 * Describes the enum common.QuoteKind.
 */
export const QuoteKindSchema: GenEnum<QuoteKind> = /*@__PURE__*/
  enumDesc(file_common, 0);

